version: '3.8'

services:
  db:
    image: mysql:8.0 # 建議用 8.0 比較穩
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aaron2k7au4a83
      MYSQL_DATABASE: whiskyjoy # 確保這裡跟後端 .env 一致
      MYSQL_USER: aaron
      MYSQL_PASSWORD: aaron2k7au4a83
    volumes:
      - mysql_data:/var/lib/mysql
      - ./whiskyjoy_sql:/docker-entrypoint-initdb.d
    networks:
      - whisky-net

  backend:
    build: ./whiskyjoy-backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ./whiskyjoy-backend/.env
    environment:
      - DB_HOST=db
    volumes:
      - ./whiskyjoy-backend:/app          # 開發時建議同步程式碼
      - ./whiskyjoy-backend/node_modules:/app/node_modules # 避免本地 node_modules 覆蓋容器
      - ./whiskyjoy-backend/public/uploads:/app/public/uploads # 圖片永久保存
    networks:
      - whisky-net

  frontend:
    build: ./whiskyjoy-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./whiskyjoy-backend/public/uploads:/usr/share/nginx/html/uploads:ro
    networks:
      - whisky-net

networks:
  whisky-net:
    driver: bridge

volumes:
  mysql_data: